language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - autoconf2.13
      - yasm
      - libgtk2.0-dev
      - libdbus-glib-1-dev
script:
  - cp .travis/mozconfig .mozconfig
  - ./mach build
